name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  IMAGE_NAME: nodejs-app

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Helm
      uses: helm/install-helm-action@v1
      with:
        version: "3.4.0"

  create-resources:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Create S3 bucket
      uses: aws-actions/amazon-s3-create-bucket@v1
      with:
        bucket-name: my-bucket

    - name: Create EKS cluster
      uses: aws-actions/eks-create-cluster@v1
      with:
        cluster-name: my-cluster
        region: ${{ env.AWS_REGION }}

  build-image:
    runs-on: ubuntu-latest
    needs: create-resources
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: ${{ env.IMAGE_NAME }}:${{ env.GITHUB_SHA }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
    - name: Deploy with Helm
      uses: Helm/helmfile-action@v1
      with:
        command: helmfile sync

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Run tests
      run: echo "Running tests"
